# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Ex-Template-XS
version:      0.05
version_from: lib/CGI/Ex/Template/XS.pm
installdirs:  site
requires:
    CGI::Ex:                       2.14
    Template::Alloy:               1.002

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
